### PR TITLE
Add ability to select the security policy used on the ELBs

### PR DESCRIPTION
**Pull request by jeffj254**
This is to resolve issue https://github.com/chef-customers/aws_native_chef_server/issues/63

### CODE REVIEW

**Comment by irvingpop** [comment]
hey @jeffj254 thanks for this!   is there any reason you can think of to still allow `ELBSecurityPolicy-2016-08` as an option for anyone?  Or even the TLS 1.1?  

I'm inclined to think nobody wanted those old ones anyway and we should simply default to the latest (not give an option, there's too many of those already)

**Comment by jeffj254** [comment]
For Chef Server and Supermarket, probably not since the clients that connect to them fully support TLS 1.2.  The only possibility I can think of is with Automate.  If somebody somewhere had an out-of-date reporting or alerting system that was pulling data from Automate it could potentially fail to connect if TLS 1.2 is enforced.

I was thinking I would add it as a parameter with the original default to prevent any unintended consequences for other users of the templates, but if you don't think that'll be a problem I can easily just switch the code to force TLS1.2 all the time.

**Comment by irvingpop** [comment]
Yeah let's force it to 1.2 - it's important we're "secure by default" and limit people's opportunities to break that. If somebody needs to modify that they'll know where to change it in their own fork.

**Comment by jeffj254** [comment]
Updated to force TLS policy to 1.2 on all ELBs

**Comment by irvingpop** [comment]
Awesome, thank you!!!

**Pull request merged**
