### PR TITLE
4.0 complete Chef stack

### PR DESCRIPTION
**Pull request by irvingpop**
The goal of the 4.0 release is to enhance the aws_native stack to also include Chef Automate 2 and Supermarket, providing the complete stack to customers.   

Those new servers are provided in non-HA flavors today, however they use the [EC2 System Autorecovery](https://aws.amazon.com/blogs/aws/new-auto-recovery-for-amazon-ec2/) feature, plus self-snapshotting of data, in order to provide more than acceptable availability. 

Major improvements to be excited about:
- [x]  Switch to CentOS and stock RHEL AMIs instead of Amazon Linux
- [x]  refactor cloudformation into nested stacks, launched by a single `main.yaml` stack
- [x]  Add a Supermarket stack (auto-recovering standalone)
- [x]  Add a Chef Automate 2 stack (auto-recovering standalone)
- [x]  Perform automatic nightly EBS snapshots of the Automate and Supermarket data volumes
- [x]  Simplify and deduplicate the IAM profiles, Security Groups and Log groups between the stacks.
- [x]  Update the `before.sh` script to automatically install awscli and cfn-init on stock RHEL
- [x]  Trim the allowed instance type list to T3, M5 and C5 classes because it's 2018 and we can all have nice things
- [x]  Update travis config

### CODE REVIEW

**Comment by irvingpop** [comment]
paging @rwc @itmustbejj @sean-horn @haidangwa @gitdave225 for visibility

**Comment by kevinreedy** [comment]
I'd love to hack on this at the ChefConf hack day! (if it's not done by then already)

**Comment by jdpc02** [comment]
This looks great and adds quite a lot of value to us customers. Thanks for listening.

**Comment by haidangwa** [comment]
I used an earlier version and needed to modify it to have unique, human
readable names for the rds instances in list environments and production.
These names were variables applied to the CFS template, like chef-server-qa
and chef-server-prod.

**Comment by irvingpop** [comment]
hey @haidangwa are you referring to the [DBInstanceIdentifier](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbinstanceidentifier) parameter?  

It comes with a pretty huge caveat that has screwed me before:
```
Important

If you specify a name, you cannot perform updates that require replacement of this resource. 
You can perform updates that require no or some interruption. If you must replace the resource,
specify a new name.
```

that's why I leave that value out.

**Comment by haidangwa** [comment]
@irvingpop,

Yes, I believe that's the one. Based on recommendation from our dba, I've
also disabled all automatic upgrades, too.
Our security policies also require encryption at rest.

**Pull request merged**
